name: ASCII85 CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y g++ make libgtest-dev
        
    - name: Build main program
      run: |
        cd ascii85
        make ascii85
        
    - name: Build and run tests
      run: |
        cd ascii85
        make test
