name: ASCII85 CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y g++
    
    - name: Make scripts executable
      run: |
        cd ascii85
        chmod +x make
    
    - name: Build and Test
      run: |
        cd ascii85
        ./ascii85_test
